name: Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a medianoche UTC
  workflow_dispatch:

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update snake animation SVG
        run: |
          curl -s https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake.svg > github-contribution-grid-snake.svg
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Actualizar animación de actividad"
          git push origin output
